# Generated by Django 4.1.2 on 2022-10-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0002_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=30)),
                ('trim', models.CharField(max_length=30)),
            ],
        ),
    ]
