# Generated by Django 4.1.2 on 2022-10-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_car_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.CharField(choices=[('O', 'Oil Change'), ('C', 'Coolant Flush'), ('B', 'Brake Pads'), ('F', 'Fuel Filter')], default='O', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
