# Generated by Django 4.1.2 on 2022-10-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_maintain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fluid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='maintain',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='maintain',
            name='date',
            field=models.DateField(verbose_name='Service Date'),
        ),
        migrations.AddField(
            model_name='car',
            name='fluids',
            field=models.ManyToManyField(to='main_app.fluid'),
        ),
    ]
